// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateFile = `-- name: ActivateFile :one
UPDATE files SET status = 'active'
WHERE id = $1 AND status = 'pending'
RETURNING id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error
`

func (q *Queries) ActivateFile(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, activateFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
		&i.ThumbS3Key,
		&i.ThumbWidth,
		&i.ThumbHeight,
		&i.ThumbStatus,
		&i.ThumbGeneratedAt,
		&i.ThumbError,
	)
	return i, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (folder_id, name, s3_key, size_bytes, mime_type, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error
`

type CreateFileParams struct {
	FolderID   pgtype.UUID `json:"folder_id"`
	Name       string      `json:"name"`
	S3Key      string      `json:"s3_key"`
	SizeBytes  int64       `json:"size_bytes"`
	MimeType   *string     `json:"mime_type"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.FolderID,
		arg.Name,
		arg.S3Key,
		arg.SizeBytes,
		arg.MimeType,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
		&i.ThumbS3Key,
		&i.ThumbWidth,
		&i.ThumbHeight,
		&i.ThumbStatus,
		&i.ThumbGeneratedAt,
		&i.ThumbError,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error FROM files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
		&i.ThumbS3Key,
		&i.ThumbWidth,
		&i.ThumbHeight,
		&i.ThumbStatus,
		&i.ThumbGeneratedAt,
		&i.ThumbError,
	)
	return i, err
}

const getFilesByIDs = `-- name: GetFilesByIDs :many
SELECT id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error FROM files WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetFilesByIDs(ctx context.Context, ids []pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
			&i.ThumbS3Key,
			&i.ThumbWidth,
			&i.ThumbHeight,
			&i.ThumbStatus,
			&i.ThumbGeneratedAt,
			&i.ThumbError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteFile = `-- name: HardDeleteFile :exec
DELETE FROM files WHERE id = $1
`

func (q *Queries) HardDeleteFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteFile, id)
	return err
}

const hardDeleteFilesMany = `-- name: HardDeleteFilesMany :exec
DELETE FROM files WHERE id = ANY($1::uuid[])
`

func (q *Queries) HardDeleteFilesMany(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteFilesMany, ids)
	return err
}

const listDeletedFiles = `-- name: ListDeletedFiles :many
SELECT f.id, f.folder_id, f.name, f.s3_key, f.size_bytes, f.mime_type, f.uploaded_by, f.status, f.created_at, f.thumb_s3_key, f.thumb_width, f.thumb_height, f.thumb_status, f.thumb_generated_at, f.thumb_error, u.name AS uploader_name
FROM files f
LEFT JOIN users u ON u.id = f.uploaded_by
WHERE f.status = 'deleted'
ORDER BY f.created_at DESC
`

type ListDeletedFilesRow struct {
	ID               pgtype.UUID        `json:"id"`
	FolderID         pgtype.UUID        `json:"folder_id"`
	Name             string             `json:"name"`
	S3Key            string             `json:"s3_key"`
	SizeBytes        int64              `json:"size_bytes"`
	MimeType         *string            `json:"mime_type"`
	UploadedBy       pgtype.UUID        `json:"uploaded_by"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ThumbS3Key       *string            `json:"thumb_s3_key"`
	ThumbWidth       *int32             `json:"thumb_width"`
	ThumbHeight      *int32             `json:"thumb_height"`
	ThumbStatus      string             `json:"thumb_status"`
	ThumbGeneratedAt pgtype.Timestamptz `json:"thumb_generated_at"`
	ThumbError       *string            `json:"thumb_error"`
	UploaderName     *string            `json:"uploader_name"`
}

func (q *Queries) ListDeletedFiles(ctx context.Context) ([]ListDeletedFilesRow, error) {
	rows, err := q.db.Query(ctx, listDeletedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletedFilesRow
	for rows.Next() {
		var i ListDeletedFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
			&i.ThumbS3Key,
			&i.ThumbWidth,
			&i.ThumbHeight,
			&i.ThumbStatus,
			&i.ThumbGeneratedAt,
			&i.ThumbError,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByFolder = `-- name: ListFilesByFolder :many
SELECT id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error FROM files
WHERE folder_id = $1 AND status = 'active'
ORDER BY name ASC
`

func (q *Queries) ListFilesByFolder(ctx context.Context, folderID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
			&i.ThumbS3Key,
			&i.ThumbWidth,
			&i.ThumbHeight,
			&i.ThumbStatus,
			&i.ThumbGeneratedAt,
			&i.ThumbError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByFolderForUser = `-- name: ListFilesByFolderForUser :many
SELECT DISTINCT f.id, f.folder_id, f.name, f.s3_key, f.size_bytes, f.mime_type, f.uploaded_by, f.status, f.created_at, f.thumb_s3_key, f.thumb_width, f.thumb_height, f.thumb_status, f.thumb_generated_at, f.thumb_error FROM files f
LEFT JOIN permissions p
  ON p.resource_type = 'file' AND p.resource_id = f.id AND p.user_id = $2
WHERE f.folder_id = $1
  AND f.status = 'active'
  AND (f.uploaded_by = $2 OR p.id IS NOT NULL)
ORDER BY f.name ASC
`

type ListFilesByFolderForUserParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListFilesByFolderForUser(ctx context.Context, arg ListFilesByFolderForUserParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByFolderForUser, arg.FolderID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
			&i.ThumbS3Key,
			&i.ThumbWidth,
			&i.ThumbHeight,
			&i.ThumbStatus,
			&i.ThumbGeneratedAt,
			&i.ThumbError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderTreeFiles = `-- name: ListFolderTreeFiles :many
WITH RECURSIVE tree AS (
  SELECT folders.id, ''::text AS relpath
  FROM folders WHERE folders.id = $1
  UNION ALL
  SELECT f.id,
         CASE WHEN t.relpath = '' THEN f.name ELSE t.relpath || '/' || f.name END
  FROM folders f JOIN tree t ON f.parent_id = t.id
)
SELECT fi.id, fi.name, fi.s3_key, fi.size_bytes, fi.uploaded_by, fi.created_at, t.relpath
FROM files fi
JOIN tree t ON fi.folder_id = t.id
WHERE fi.status = 'active'
ORDER BY t.relpath, fi.name
`

type ListFolderTreeFilesRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	S3Key      string             `json:"s3_key"`
	SizeBytes  int64              `json:"size_bytes"`
	UploadedBy pgtype.UUID        `json:"uploaded_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Relpath    string             `json:"relpath"`
}

func (q *Queries) ListFolderTreeFiles(ctx context.Context, id pgtype.UUID) ([]ListFolderTreeFilesRow, error) {
	rows, err := q.db.Query(ctx, listFolderTreeFiles, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderTreeFilesRow
	for rows.Next() {
		var i ListFolderTreeFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.Relpath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderTreeFolders = `-- name: ListFolderTreeFolders :many
WITH RECURSIVE tree AS (
  SELECT folders.id, folders.parent_id, ''::text AS relpath
  FROM folders WHERE folders.id = $1
  UNION ALL
  SELECT f.id, f.parent_id,
         CASE WHEN t.relpath = '' THEN f.name ELSE t.relpath || '/' || f.name END
  FROM folders f JOIN tree t ON f.parent_id = t.id
)
SELECT id, relpath FROM tree ORDER BY relpath
`

type ListFolderTreeFoldersRow struct {
	ID      pgtype.UUID `json:"id"`
	Relpath string      `json:"relpath"`
}

func (q *Queries) ListFolderTreeFolders(ctx context.Context, id pgtype.UUID) ([]ListFolderTreeFoldersRow, error) {
	rows, err := q.db.Query(ctx, listFolderTreeFolders, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderTreeFoldersRow
	for rows.Next() {
		var i ListFolderTreeFoldersRow
		if err := rows.Scan(&i.ID, &i.Relpath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFiles = `-- name: ListRootFiles :many
SELECT id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error FROM files
WHERE folder_id IS NULL AND status = 'active'
ORDER BY name ASC
`

func (q *Queries) ListRootFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, listRootFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
			&i.ThumbS3Key,
			&i.ThumbWidth,
			&i.ThumbHeight,
			&i.ThumbStatus,
			&i.ThumbGeneratedAt,
			&i.ThumbError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFilesForUser = `-- name: ListRootFilesForUser :many
SELECT DISTINCT f.id, f.folder_id, f.name, f.s3_key, f.size_bytes, f.mime_type, f.uploaded_by, f.status, f.created_at, f.thumb_s3_key, f.thumb_width, f.thumb_height, f.thumb_status, f.thumb_generated_at, f.thumb_error FROM files f
LEFT JOIN permissions p
  ON p.resource_type = 'file' AND p.resource_id = f.id AND p.user_id = $1
WHERE f.folder_id IS NULL
  AND f.status = 'active'
  AND (f.uploaded_by = $1 OR p.id IS NOT NULL)
ORDER BY f.name ASC
`

func (q *Queries) ListRootFilesForUser(ctx context.Context, userID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listRootFilesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
			&i.ThumbS3Key,
			&i.ThumbWidth,
			&i.ThumbHeight,
			&i.ThumbStatus,
			&i.ThumbGeneratedAt,
			&i.ThumbError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFilesToFolder = `-- name: MoveFilesToFolder :exec
UPDATE files SET folder_id = $1
WHERE id = ANY($2::uuid[]) AND status = 'active'
`

type MoveFilesToFolderParams struct {
	FolderID pgtype.UUID   `json:"folder_id"`
	FileIds  []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) MoveFilesToFolder(ctx context.Context, arg MoveFilesToFolderParams) error {
	_, err := q.db.Exec(ctx, moveFilesToFolder, arg.FolderID, arg.FileIds)
	return err
}

const restoreFile = `-- name: RestoreFile :one
UPDATE files SET status = 'active'
WHERE id = $1 AND status = 'deleted'
RETURNING id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error
`

func (q *Queries) RestoreFile(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, restoreFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
		&i.ThumbS3Key,
		&i.ThumbWidth,
		&i.ThumbHeight,
		&i.ThumbStatus,
		&i.ThumbGeneratedAt,
		&i.ThumbError,
	)
	return i, err
}

const searchFiles = `-- name: SearchFiles :many
SELECT id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error FROM files
WHERE status = 'active' AND name ILIKE '%' || $1 || '%'
ORDER BY name ASC
LIMIT 100
`

func (q *Queries) SearchFiles(ctx context.Context, dollar_1 *string) ([]File, error) {
	rows, err := q.db.Query(ctx, searchFiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
			&i.ThumbS3Key,
			&i.ThumbWidth,
			&i.ThumbHeight,
			&i.ThumbStatus,
			&i.ThumbGeneratedAt,
			&i.ThumbError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE files SET status = 'deleted' WHERE id = $1
`

func (q *Queries) SoftDeleteFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFile, id)
	return err
}

const softDeleteFilesMany = `-- name: SoftDeleteFilesMany :exec
UPDATE files SET status = 'deleted'
WHERE id = ANY($1::uuid[]) AND status = 'active'
`

func (q *Queries) SoftDeleteFilesMany(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFilesMany, ids)
	return err
}

const updateFileName = `-- name: UpdateFileName :one
UPDATE files SET name = $1 WHERE id = $2 AND status = 'active' RETURNING id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error
`

type UpdateFileNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateFileName(ctx context.Context, arg UpdateFileNameParams) (File, error) {
	row := q.db.QueryRow(ctx, updateFileName, arg.Name, arg.ID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
		&i.ThumbS3Key,
		&i.ThumbWidth,
		&i.ThumbHeight,
		&i.ThumbStatus,
		&i.ThumbGeneratedAt,
		&i.ThumbError,
	)
	return i, err
}
