// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateFile = `-- name: ActivateFile :one
UPDATE files SET status = 'active'
WHERE id = $1 AND status = 'pending'
RETURNING id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at
`

func (q *Queries) ActivateFile(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, activateFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (folder_id, name, s3_key, size_bytes, mime_type, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at
`

type CreateFileParams struct {
	FolderID   pgtype.UUID `json:"folder_id"`
	Name       string      `json:"name"`
	S3Key      string      `json:"s3_key"`
	SizeBytes  int64       `json:"size_bytes"`
	MimeType   *string     `json:"mime_type"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.FolderID,
		arg.Name,
		arg.S3Key,
		arg.SizeBytes,
		arg.MimeType,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at FROM files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listFilesByFolder = `-- name: ListFilesByFolder :many
SELECT id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at FROM files
WHERE folder_id = $1 AND status = 'active'
ORDER BY name ASC
`

func (q *Queries) ListFilesByFolder(ctx context.Context, folderID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByFolderForUser = `-- name: ListFilesByFolderForUser :many
SELECT DISTINCT f.id, f.folder_id, f.name, f.s3_key, f.size_bytes, f.mime_type, f.uploaded_by, f.status, f.created_at FROM files f
LEFT JOIN permissions p
  ON p.resource_type = 'file' AND p.resource_id = f.id AND p.user_id = $2
WHERE f.folder_id = $1
  AND f.status = 'active'
  AND (f.uploaded_by = $2 OR p.id IS NOT NULL)
ORDER BY f.name ASC
`

type ListFilesByFolderForUserParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListFilesByFolderForUser(ctx context.Context, arg ListFilesByFolderForUserParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByFolderForUser, arg.FolderID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFiles = `-- name: ListRootFiles :many
SELECT id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at FROM files
WHERE folder_id IS NULL AND status = 'active'
ORDER BY name ASC
`

func (q *Queries) ListRootFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, listRootFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFilesForUser = `-- name: ListRootFilesForUser :many
SELECT DISTINCT f.id, f.folder_id, f.name, f.s3_key, f.size_bytes, f.mime_type, f.uploaded_by, f.status, f.created_at FROM files f
LEFT JOIN permissions p
  ON p.resource_type = 'file' AND p.resource_id = f.id AND p.user_id = $1
WHERE f.folder_id IS NULL
  AND f.status = 'active'
  AND (f.uploaded_by = $1 OR p.id IS NOT NULL)
ORDER BY f.name ASC
`

func (q *Queries) ListRootFilesForUser(ctx context.Context, userID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listRootFilesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE files SET status = 'deleted' WHERE id = $1
`

func (q *Queries) SoftDeleteFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFile, id)
	return err
}

const updateFileName = `-- name: UpdateFileName :one
UPDATE files SET name = $1 WHERE id = $2 AND status = 'active' RETURNING id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at
`

type UpdateFileNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateFileName(ctx context.Context, arg UpdateFileNameParams) (File, error) {
	row := q.db.QueryRow(ctx, updateFileName, arg.Name, arg.ID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
