// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFolderItems = `-- name: CountFolderItems :one
SELECT COUNT(*) FROM (
  SELECT id FROM folders WHERE parent_id = $1
  UNION ALL
  SELECT id FROM files WHERE folder_id = $1 AND status = 'active'
) sub
`

func (q *Queries) CountFolderItems(ctx context.Context, parentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFolderItems, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (name, parent_id, owner_id)
VALUES ($1, $2, $3)
RETURNING id, parent_id, name, owner_id, created_at
`

type CreateFolderParams struct {
	Name     string      `json:"name"`
	ParentID pgtype.UUID `json:"parent_id"`
	OwnerID  pgtype.UUID `json:"owner_id"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.Name, arg.ParentID, arg.OwnerID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const getFolder = `-- name: GetFolder :one
SELECT id, parent_id, name, owner_id, created_at FROM folders WHERE id = $1
`

func (q *Queries) GetFolder(ctx context.Context, id pgtype.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const listFoldersByParent = `-- name: ListFoldersByParent :many
SELECT id, parent_id, name, owner_id, created_at FROM folders
WHERE parent_id = $1
ORDER BY name ASC
`

func (q *Queries) ListFoldersByParent(ctx context.Context, parentID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByParentForUser = `-- name: ListFoldersByParentForUser :many
SELECT DISTINCT f.id, f.parent_id, f.name, f.owner_id, f.created_at FROM folders f
LEFT JOIN permissions p
  ON p.resource_type = 'folder' AND p.resource_id = f.id AND p.user_id = $2
WHERE f.parent_id = $1
  AND (f.owner_id = $2 OR p.id IS NOT NULL)
ORDER BY f.name ASC
`

type ListFoldersByParentForUserParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListFoldersByParentForUser(ctx context.Context, arg ListFoldersByParentForUserParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByParentForUser, arg.ParentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFolders = `-- name: ListRootFolders :many
SELECT id, parent_id, name, owner_id, created_at FROM folders
WHERE parent_id IS NULL
ORDER BY name ASC
`

func (q *Queries) ListRootFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listRootFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFoldersForUser = `-- name: ListRootFoldersForUser :many
SELECT DISTINCT f.id, f.parent_id, f.name, f.owner_id, f.created_at FROM folders f
LEFT JOIN permissions p
  ON p.resource_type = 'folder' AND p.resource_id = f.id AND p.user_id = $1
WHERE f.parent_id IS NULL
  AND (f.owner_id = $1 OR p.id IS NOT NULL)
ORDER BY f.name ASC
`

func (q *Queries) ListRootFoldersForUser(ctx context.Context, userID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listRootFoldersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolderName = `-- name: UpdateFolderName :one
UPDATE folders SET name = $1 WHERE id = $2 RETURNING id, parent_id, name, owner_id, created_at
`

type UpdateFolderNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateFolderName(ctx context.Context, arg UpdateFolderNameParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolderName, arg.Name, arg.ID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}
