// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Meta         []byte             `json:"meta"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID               pgtype.UUID        `json:"id"`
	FolderID         pgtype.UUID        `json:"folder_id"`
	Name             string             `json:"name"`
	S3Key            string             `json:"s3_key"`
	SizeBytes        int64              `json:"size_bytes"`
	MimeType         *string            `json:"mime_type"`
	UploadedBy       pgtype.UUID        `json:"uploaded_by"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ThumbS3Key       *string            `json:"thumb_s3_key"`
	ThumbWidth       *int32             `json:"thumb_width"`
	ThumbHeight      *int32             `json:"thumb_height"`
	ThumbStatus      string             `json:"thumb_status"`
	ThumbGeneratedAt pgtype.Timestamptz `json:"thumb_generated_at"`
	ThumbError       *string            `json:"thumb_error"`
}

type Folder struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Name      string             `json:"name"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Level        string             `json:"level"`
	GrantedBy    pgtype.UUID        `json:"granted_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Share struct {
	ID           pgtype.UUID        `json:"id"`
	FileID       pgtype.UUID        `json:"file_id"`
	Slug         string             `json:"slug"`
	ShareType    string             `json:"share_type"`
	PasswordHash *string            `json:"password_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	MaxViews     *int32             `json:"max_views"`
	ViewCount    int32              `json:"view_count"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FolderID     pgtype.UUID        `json:"folder_id"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	PasswordHash string             `json:"password_hash"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ZipJob struct {
	ID           pgtype.UUID        `json:"id"`
	FolderID     pgtype.UUID        `json:"folder_id"`
	ShareID      pgtype.UUID        `json:"share_id"`
	Status       string             `json:"status"`
	S3Key        *string            `json:"s3_key"`
	SizeBytes    int64              `json:"size_bytes"`
	FileCount    int32              `json:"file_count"`
	ContentBytes int64              `json:"content_bytes"`
	Error        *string            `json:"error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}
