// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pagination.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT COUNT(*) FROM audit_log
`

func (q *Queries) CountAuditLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFiles = `-- name: CountFiles :one
SELECT COUNT(*) FROM files
WHERE folder_id IS NOT DISTINCT FROM $1
  AND status = 'active'
`

func (q *Queries) CountFiles(ctx context.Context, folderID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFiles, folderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAuditLogPage = `-- name: ListAuditLogPage :many
SELECT
  al.id,
  al.user_id,
  al.action,
  al.resource_type,
  al.resource_id,
  al.meta,
  al.created_at,
  u.name  AS actor_name,
  u.email AS actor_email
FROM audit_log al
LEFT JOIN users u ON u.id = al.user_id
ORDER BY al.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAuditLogPageRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Meta         []byte             `json:"meta"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ActorName    *string            `json:"actor_name"`
	ActorEmail   *string            `json:"actor_email"`
}

func (q *Queries) ListAuditLogPage(ctx context.Context, arg ListAuditLogPageParams) ([]ListAuditLogPageRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogPageRow
	for rows.Next() {
		var i ListAuditLogPageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Meta,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesPage = `-- name: ListFilesPage :many
SELECT id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at FROM files
WHERE folder_id IS NOT DISTINCT FROM $1
  AND status = 'active'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFilesPageParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListFilesPage(ctx context.Context, arg ListFilesPageParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesPage, arg.FolderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileSizeAndStatus = `-- name: UpdateFileSizeAndStatus :one
UPDATE files SET size_bytes = $1, status = $2 WHERE id = $3 RETURNING id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at
`

type UpdateFileSizeAndStatusParams struct {
	SizeBytes int64       `json:"size_bytes"`
	Status    string      `json:"status"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateFileSizeAndStatus(ctx context.Context, arg UpdateFileSizeAndStatusParams) (File, error) {
	row := q.db.QueryRow(ctx, updateFileSizeAndStatus, arg.SizeBytes, arg.Status, arg.ID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
