// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPermission = `-- name: CheckPermission :one
SELECT EXISTS(
  SELECT 1 FROM permissions
  WHERE user_id       = $1
    AND resource_type = $2
    AND resource_id   = $3
)
`

type CheckPermissionParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
}

func (q *Queries) CheckPermission(ctx context.Context, arg CheckPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPermission, arg.UserID, arg.ResourceType, arg.ResourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const grantPermission = `-- name: GrantPermission :one
INSERT INTO permissions (user_id, resource_type, resource_id, level, granted_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, resource_type, resource_id) DO UPDATE
  SET level      = EXCLUDED.level,
      granted_by = EXCLUDED.granted_by
RETURNING id, user_id, resource_type, resource_id, level, granted_by, created_at
`

type GrantPermissionParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	Level        string      `json:"level"`
	GrantedBy    pgtype.UUID `json:"granted_by"`
}

func (q *Queries) GrantPermission(ctx context.Context, arg GrantPermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, grantPermission,
		arg.UserID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Level,
		arg.GrantedBy,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Level,
		&i.GrantedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissionsForResource = `-- name: ListPermissionsForResource :many
SELECT
  p.id,
  p.user_id,
  p.resource_type,
  p.resource_id,
  p.level,
  p.created_at,
  u.name  AS grantee_name,
  u.email AS grantee_email
FROM permissions p
JOIN users u ON u.id = p.user_id
WHERE p.resource_type = $1 AND p.resource_id = $2
ORDER BY u.name ASC
`

type ListPermissionsForResourceParams struct {
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
}

type ListPermissionsForResourceRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Level        string             `json:"level"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	GranteeName  string             `json:"grantee_name"`
	GranteeEmail string             `json:"grantee_email"`
}

func (q *Queries) ListPermissionsForResource(ctx context.Context, arg ListPermissionsForResourceParams) ([]ListPermissionsForResourceRow, error) {
	rows, err := q.db.Query(ctx, listPermissionsForResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsForResourceRow
	for rows.Next() {
		var i ListPermissionsForResourceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Level,
			&i.CreatedAt,
			&i.GranteeName,
			&i.GranteeEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePermission = `-- name: RevokePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) RevokePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokePermission, id)
	return err
}
