// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateFile(ctx context.Context, id pgtype.UUID) (File, error)
	CheckPermission(ctx context.Context, arg CheckPermissionParams) (bool, error)
	ClaimNextPendingZipJob(ctx context.Context) (ZipJob, error)
	ClaimPendingThumbnail(ctx context.Context) (File, error)
	CountAuditLog(ctx context.Context) (int64, error)
	CountFiles(ctx context.Context, folderID pgtype.UUID) (int64, error)
	CountFolderItems(ctx context.Context, parentID pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateFolderShare(ctx context.Context, arg CreateFolderShareParams) (Share, error)
	CreateShare(ctx context.Context, arg CreateShareParams) (Share, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateZipJob(ctx context.Context, arg CreateZipJobParams) (ZipJob, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) (User, error)
	DeleteFolder(ctx context.Context, id pgtype.UUID) error
	FailStaleRunningZipJobs(ctx context.Context) error
	GetActiveShareByFileID(ctx context.Context, fileID pgtype.UUID) (Share, error)
	GetActiveShareByFolderID(ctx context.Context, folderID pgtype.UUID) (Share, error)
	GetFile(ctx context.Context, id pgtype.UUID) (File, error)
	GetFilesByIDs(ctx context.Context, ids []pgtype.UUID) ([]File, error)
	GetFolder(ctx context.Context, id pgtype.UUID) (Folder, error)
	GetReusableZipJob(ctx context.Context, arg GetReusableZipJobParams) (ZipJob, error)
	GetShare(ctx context.Context, id pgtype.UUID) (Share, error)
	GetShareBySlug(ctx context.Context, slug string) (Share, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetZipJob(ctx context.Context, id pgtype.UUID) (ZipJob, error)
	GrantPermission(ctx context.Context, arg GrantPermissionParams) (Permission, error)
	HardDeleteFile(ctx context.Context, id pgtype.UUID) error
	HardDeleteFilesMany(ctx context.Context, ids []pgtype.UUID) error
	IncrementShareViewCount(ctx context.Context, id pgtype.UUID) error
	ListAllFolders(ctx context.Context) ([]Folder, error)
	ListAllShares(ctx context.Context) ([]ListAllSharesRow, error)
	ListAuditLogByAction(ctx context.Context, arg ListAuditLogByActionParams) ([]ListAuditLogByActionRow, error)
	ListAuditLogPage(ctx context.Context, arg ListAuditLogPageParams) ([]ListAuditLogPageRow, error)
	ListDeletedFiles(ctx context.Context) ([]ListDeletedFilesRow, error)
	ListExpiredReadyZipJobs(ctx context.Context) ([]ZipJob, error)
	ListFilesByFolder(ctx context.Context, folderID pgtype.UUID) ([]File, error)
	ListFilesByFolderForUser(ctx context.Context, arg ListFilesByFolderForUserParams) ([]File, error)
	ListFilesMissingThumbnails(ctx context.Context, limit int32) ([]File, error)
	ListFilesPage(ctx context.Context, arg ListFilesPageParams) ([]File, error)
	ListFolderTreeFiles(ctx context.Context, id pgtype.UUID) ([]ListFolderTreeFilesRow, error)
	ListFolderTreeFolders(ctx context.Context, id pgtype.UUID) ([]ListFolderTreeFoldersRow, error)
	ListFoldersByParent(ctx context.Context, parentID pgtype.UUID) ([]Folder, error)
	ListFoldersByParentForUser(ctx context.Context, arg ListFoldersByParentForUserParams) ([]Folder, error)
	ListPermissionsForResource(ctx context.Context, arg ListPermissionsForResourceParams) ([]ListPermissionsForResourceRow, error)
	ListRecentAuditLog(ctx context.Context, limit int32) ([]ListRecentAuditLogRow, error)
	ListRootFiles(ctx context.Context) ([]File, error)
	ListRootFilesForUser(ctx context.Context, userID pgtype.UUID) ([]File, error)
	ListRootFolders(ctx context.Context) ([]Folder, error)
	ListRootFoldersForUser(ctx context.Context, userID pgtype.UUID) ([]Folder, error)
	ListSharesByCreator(ctx context.Context, createdBy pgtype.UUID) ([]ListSharesByCreatorRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkThumbnailFailed(ctx context.Context, arg MarkThumbnailFailedParams) error
	MarkThumbnailReady(ctx context.Context, arg MarkThumbnailReadyParams) error
	MarkZipJobExpired(ctx context.Context, id pgtype.UUID) error
	MarkZipJobFailed(ctx context.Context, arg MarkZipJobFailedParams) error
	MarkZipJobReady(ctx context.Context, arg MarkZipJobReadyParams) error
	MoveFileToFolder(ctx context.Context, arg MoveFileToFolderParams) (File, error)
	MoveFilesToFolder(ctx context.Context, arg MoveFilesToFolderParams) error
	ResetFailedThumbnails(ctx context.Context) error
	ResetPendingThumbnails(ctx context.Context) error
	RestoreFile(ctx context.Context, id pgtype.UUID) (File, error)
	RevokePermission(ctx context.Context, id pgtype.UUID) error
	RevokeShare(ctx context.Context, id pgtype.UUID) error
	SearchFiles(ctx context.Context, dollar_1 *string) ([]File, error)
	SearchFolders(ctx context.Context, dollar_1 *string) ([]Folder, error)
	SoftDeleteFile(ctx context.Context, id pgtype.UUID) error
	SoftDeleteFilesMany(ctx context.Context, ids []pgtype.UUID) error
	UpdateFileName(ctx context.Context, arg UpdateFileNameParams) (File, error)
	UpdateFileSizeAndStatus(ctx context.Context, arg UpdateFileSizeAndStatusParams) (File, error)
	UpdateFolderName(ctx context.Context, arg UpdateFolderNameParams) (Folder, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
