// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateFile(ctx context.Context, id pgtype.UUID) (File, error)
	CountFolderItems(ctx context.Context, parentID pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) (User, error)
	DeleteFolder(ctx context.Context, id pgtype.UUID) error
	GetFile(ctx context.Context, id pgtype.UUID) (File, error)
	GetFolder(ctx context.Context, id pgtype.UUID) (Folder, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListFilesByFolder(ctx context.Context, folderID pgtype.UUID) ([]File, error)
	ListFilesByFolderForUser(ctx context.Context, arg ListFilesByFolderForUserParams) ([]File, error)
	ListFoldersByParent(ctx context.Context, parentID pgtype.UUID) ([]Folder, error)
	ListFoldersByParentForUser(ctx context.Context, arg ListFoldersByParentForUserParams) ([]Folder, error)
	ListRootFiles(ctx context.Context) ([]File, error)
	ListRootFilesForUser(ctx context.Context, userID pgtype.UUID) ([]File, error)
	ListRootFolders(ctx context.Context) ([]Folder, error)
	ListRootFoldersForUser(ctx context.Context, userID pgtype.UUID) ([]Folder, error)
	ListUsers(ctx context.Context) ([]User, error)
	SoftDeleteFile(ctx context.Context, id pgtype.UUID) error
	UpdateFolderName(ctx context.Context, arg UpdateFolderNameParams) (Folder, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
