// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shares.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShare = `-- name: CreateShare :one
INSERT INTO shares (file_id, slug, share_type, expires_at, created_by)
VALUES ($1, $2, 'public', $3, $4)
RETURNING id, file_id, slug, share_type, password_hash, expires_at, max_views, view_count, created_by, created_at
`

type CreateShareParams struct {
	FileID    pgtype.UUID        `json:"file_id"`
	Slug      string             `json:"slug"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	row := q.db.QueryRow(ctx, createShare,
		arg.FileID,
		arg.Slug,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Slug,
		&i.ShareType,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveShareByFileID = `-- name: GetActiveShareByFileID :one
SELECT id, file_id, slug, share_type, password_hash, expires_at, max_views, view_count, created_by, created_at FROM shares
WHERE file_id = $1
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveShareByFileID(ctx context.Context, fileID pgtype.UUID) (Share, error) {
	row := q.db.QueryRow(ctx, getActiveShareByFileID, fileID)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Slug,
		&i.ShareType,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getShareBySlug = `-- name: GetShareBySlug :one
SELECT id, file_id, slug, share_type, password_hash, expires_at, max_views, view_count, created_by, created_at FROM shares WHERE slug = $1
`

func (q *Queries) GetShareBySlug(ctx context.Context, slug string) (Share, error) {
	row := q.db.QueryRow(ctx, getShareBySlug, slug)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Slug,
		&i.ShareType,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const incrementShareViewCount = `-- name: IncrementShareViewCount :exec
UPDATE shares SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementShareViewCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementShareViewCount, id)
	return err
}
