// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: thumbnails.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingThumbnail = `-- name: ClaimPendingThumbnail :one
UPDATE files
SET thumb_status = 'pending'
WHERE id = (
  SELECT id FROM files
  WHERE status = 'active'
    AND mime_type IN ('image/jpeg', 'image/png', 'image/gif', 'image/webp')
    AND thumb_status = 'none'
  ORDER BY created_at ASC
  LIMIT 1
)
  AND thumb_status = 'none'
RETURNING id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error
`

func (q *Queries) ClaimPendingThumbnail(ctx context.Context) (File, error) {
	row := q.db.QueryRow(ctx, claimPendingThumbnail)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.Name,
		&i.S3Key,
		&i.SizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
		&i.ThumbS3Key,
		&i.ThumbWidth,
		&i.ThumbHeight,
		&i.ThumbStatus,
		&i.ThumbGeneratedAt,
		&i.ThumbError,
	)
	return i, err
}

const listFilesMissingThumbnails = `-- name: ListFilesMissingThumbnails :many
SELECT id, folder_id, name, s3_key, size_bytes, mime_type, uploaded_by, status, created_at, thumb_s3_key, thumb_width, thumb_height, thumb_status, thumb_generated_at, thumb_error FROM files
WHERE status = 'active'
  AND mime_type IN ('image/jpeg', 'image/png', 'image/gif', 'image/webp')
  AND thumb_status <> 'ready'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListFilesMissingThumbnails(ctx context.Context, limit int32) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesMissingThumbnails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.S3Key,
			&i.SizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
			&i.ThumbS3Key,
			&i.ThumbWidth,
			&i.ThumbHeight,
			&i.ThumbStatus,
			&i.ThumbGeneratedAt,
			&i.ThumbError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markThumbnailFailed = `-- name: MarkThumbnailFailed :exec
UPDATE files
SET thumb_status = 'failed',
    thumb_error = $1
WHERE id = $2
`

type MarkThumbnailFailedParams struct {
	ThumbError *string     `json:"thumb_error"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) MarkThumbnailFailed(ctx context.Context, arg MarkThumbnailFailedParams) error {
	_, err := q.db.Exec(ctx, markThumbnailFailed, arg.ThumbError, arg.ID)
	return err
}

const markThumbnailReady = `-- name: MarkThumbnailReady :exec
UPDATE files
SET thumb_s3_key = $1,
    thumb_width = $2,
    thumb_height = $3,
    thumb_generated_at = NOW(),
    thumb_status = 'ready',
    thumb_error = NULL
WHERE id = $4
`

type MarkThumbnailReadyParams struct {
	ThumbS3Key  *string     `json:"thumb_s3_key"`
	ThumbWidth  *int32      `json:"thumb_width"`
	ThumbHeight *int32      `json:"thumb_height"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) MarkThumbnailReady(ctx context.Context, arg MarkThumbnailReadyParams) error {
	_, err := q.db.Exec(ctx, markThumbnailReady,
		arg.ThumbS3Key,
		arg.ThumbWidth,
		arg.ThumbHeight,
		arg.ID,
	)
	return err
}

const resetFailedThumbnails = `-- name: ResetFailedThumbnails :exec
UPDATE files SET thumb_status = 'none' WHERE thumb_status = 'failed'
`

func (q *Queries) ResetFailedThumbnails(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetFailedThumbnails)
	return err
}

const resetPendingThumbnails = `-- name: ResetPendingThumbnails :exec
UPDATE files SET thumb_status = 'none' WHERE thumb_status = 'pending'
`

func (q *Queries) ResetPendingThumbnails(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetPendingThumbnails)
	return err
}
