// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zipjobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingZipJob = `-- name: ClaimNextPendingZipJob :one
UPDATE zip_jobs SET status = 'running'
WHERE id = (
  SELECT id FROM zip_jobs
  WHERE status = 'pending'
  ORDER BY created_at
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, folder_id, share_id, status, s3_key, size_bytes, file_count, content_bytes, error, created_at, expires_at
`

func (q *Queries) ClaimNextPendingZipJob(ctx context.Context) (ZipJob, error) {
	row := q.db.QueryRow(ctx, claimNextPendingZipJob)
	var i ZipJob
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ShareID,
		&i.Status,
		&i.S3Key,
		&i.SizeBytes,
		&i.FileCount,
		&i.ContentBytes,
		&i.Error,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createZipJob = `-- name: CreateZipJob :one
INSERT INTO zip_jobs (folder_id, share_id, file_count, content_bytes)
VALUES ($1, $2, $3, $4)
RETURNING id, folder_id, share_id, status, s3_key, size_bytes, file_count, content_bytes, error, created_at, expires_at
`

type CreateZipJobParams struct {
	FolderID     pgtype.UUID `json:"folder_id"`
	ShareID      pgtype.UUID `json:"share_id"`
	FileCount    int32       `json:"file_count"`
	ContentBytes int64       `json:"content_bytes"`
}

func (q *Queries) CreateZipJob(ctx context.Context, arg CreateZipJobParams) (ZipJob, error) {
	row := q.db.QueryRow(ctx, createZipJob,
		arg.FolderID,
		arg.ShareID,
		arg.FileCount,
		arg.ContentBytes,
	)
	var i ZipJob
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ShareID,
		&i.Status,
		&i.S3Key,
		&i.SizeBytes,
		&i.FileCount,
		&i.ContentBytes,
		&i.Error,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const failStaleRunningZipJobs = `-- name: FailStaleRunningZipJobs :exec
UPDATE zip_jobs SET status = 'failed', error = 'interrupted by server restart'
WHERE status = 'running'
`

func (q *Queries) FailStaleRunningZipJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, failStaleRunningZipJobs)
	return err
}

const getReusableZipJob = `-- name: GetReusableZipJob :one
SELECT id, folder_id, share_id, status, s3_key, size_bytes, file_count, content_bytes, error, created_at, expires_at FROM zip_jobs
WHERE folder_id = $1
  AND (
    status IN ('pending', 'running')
    OR (
      status = 'ready'
      AND expires_at > NOW()
      AND file_count = $2
      AND content_bytes = $3
      AND created_at > $4
    )
  )
ORDER BY created_at DESC
LIMIT 1
`

type GetReusableZipJobParams struct {
	FolderID     pgtype.UUID        `json:"folder_id"`
	FileCount    int32              `json:"file_count"`
	ContentBytes int64              `json:"content_bytes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetReusableZipJob(ctx context.Context, arg GetReusableZipJobParams) (ZipJob, error) {
	row := q.db.QueryRow(ctx, getReusableZipJob,
		arg.FolderID,
		arg.FileCount,
		arg.ContentBytes,
		arg.CreatedAt,
	)
	var i ZipJob
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ShareID,
		&i.Status,
		&i.S3Key,
		&i.SizeBytes,
		&i.FileCount,
		&i.ContentBytes,
		&i.Error,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getZipJob = `-- name: GetZipJob :one
SELECT id, folder_id, share_id, status, s3_key, size_bytes, file_count, content_bytes, error, created_at, expires_at FROM zip_jobs WHERE id = $1
`

func (q *Queries) GetZipJob(ctx context.Context, id pgtype.UUID) (ZipJob, error) {
	row := q.db.QueryRow(ctx, getZipJob, id)
	var i ZipJob
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ShareID,
		&i.Status,
		&i.S3Key,
		&i.SizeBytes,
		&i.FileCount,
		&i.ContentBytes,
		&i.Error,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExpiredReadyZipJobs = `-- name: ListExpiredReadyZipJobs :many
SELECT id, folder_id, share_id, status, s3_key, size_bytes, file_count, content_bytes, error, created_at, expires_at FROM zip_jobs WHERE status = 'ready' AND expires_at < NOW()
`

func (q *Queries) ListExpiredReadyZipJobs(ctx context.Context) ([]ZipJob, error) {
	rows, err := q.db.Query(ctx, listExpiredReadyZipJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZipJob
	for rows.Next() {
		var i ZipJob
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ShareID,
			&i.Status,
			&i.S3Key,
			&i.SizeBytes,
			&i.FileCount,
			&i.ContentBytes,
			&i.Error,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markZipJobExpired = `-- name: MarkZipJobExpired :exec
UPDATE zip_jobs SET status = 'failed', error = 'expired' WHERE id = $1
`

func (q *Queries) MarkZipJobExpired(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markZipJobExpired, id)
	return err
}

const markZipJobFailed = `-- name: MarkZipJobFailed :exec
UPDATE zip_jobs SET status = 'failed', error = $2 WHERE id = $1
`

type MarkZipJobFailedParams struct {
	ID    pgtype.UUID `json:"id"`
	Error *string     `json:"error"`
}

func (q *Queries) MarkZipJobFailed(ctx context.Context, arg MarkZipJobFailedParams) error {
	_, err := q.db.Exec(ctx, markZipJobFailed, arg.ID, arg.Error)
	return err
}

const markZipJobReady = `-- name: MarkZipJobReady :exec
UPDATE zip_jobs
SET status = 'ready', s3_key = $2, size_bytes = $3, expires_at = NOW() + INTERVAL '24 hours'
WHERE id = $1
`

type MarkZipJobReadyParams struct {
	ID        pgtype.UUID `json:"id"`
	S3Key     *string     `json:"s3_key"`
	SizeBytes int64       `json:"size_bytes"`
}

func (q *Queries) MarkZipJobReady(ctx context.Context, arg MarkZipJobReadyParams) error {
	_, err := q.db.Exec(ctx, markZipJobReady, arg.ID, arg.S3Key, arg.SizeBytes)
	return err
}
